<a href="https://colab.research.google.com/github/spoorthybalaji/Online-Workshop-on-Applications-of-Python-programming-in-DA-and-ML/blob/master/Day3_Session2_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a Pandas program to create and display a one-dimensional array using series  containing  event numbers upto 10000
tip : use List Comprehension
ds = pd.Series([0,2, 4, 6, 8..... 10000])

In [ ]:
import pandas as pd
ds=pd.Series([x for x in range(1000) if x%2==0])
ds

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64

2. Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and  after convertion print its type 

In [ ]:
import pandas as pd
ds=pd.Series([x for x in range(1000,2001) if x%5==0])
ds



0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
196    1980
197    1985
198    1990
199    1995
200    2000
Length: 201, dtype: int64

3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


4. Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]

In [ ]:
import pandas as pd
ds1=pd.Series([2, 4, 6, 8, 10])
ds2=pd.Series([1, 3, 5, 7, 10])
print("Series1:")
ds1
print("Series2:")
ds2
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
Series2:
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


5. Write a Pandas program to convert a NumPy array to a Pandas series. 
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]

In [ ]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


6. Write a Pandas program to convert a given Series to an array.Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


7. Write a Pandas program to create a subsets of a given series based on value and condition.Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5

In [ ]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


8. Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [ ]:
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


9. Write a Pandas program to get the elements of an array values into column-wise.Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


10. Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

In [ ]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])

First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


11. Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields 
(movie_metadata.csv file).

In [ ]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
import pandas as pd
xyz = pd.read_csv('movies_metadata.csv') 
print(xyz.head(1))

   adult  ... vote_count
0  False  ...     5415.0

[1 rows x 24 columns]


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
seventh_movie = df.iloc[3]
print("Details of the seventh movie:")
print(seventh_movie)

Details of the seventh movie:
adult                                                                False
belongs_to_collection                                                  NaN
budget                                                            16000000
genres                   [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
homepage                                                               NaN
id                                                                   31357
imdb_id                                                          tt0114885
original_language                                                       en
original_title                                           Waiting to Exhale
overview                 Cheated on, mistreated and stepped on, the wom...
popularity                                                         3.85949
poster_path                               /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
production_companies     [{'name': 'Twentieth Century Fox Film Corpora

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


12. Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields 

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
result = df[['title', 'genres']]
print("Details of title and genres:")
print(result)

Details of title and genres:
                             title                                             genres
0                        Toy Story  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1                          Jumanji  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2                 Grumpier Old Men  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3                Waiting to Exhale  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4      Father of the Bride Part II                     [{'id': 35, 'name': 'Comedy'}]
...                            ...                                                ...
45461                       Subdue  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462          Century of Birthing                      [{'id': 18, 'name': 'Drama'}]
45463                     Betrayal  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464             Satan Triumphant                                                 []
45465                    

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


13. Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

In [ ]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x)

Original Array:
[[0.06983272 0.28980912 0.63569294 0.24733063]
 [0.91820096 0.03578891 0.24069499 0.33000368]
 [0.97149688 0.86510127 0.56765916 0.82670019]
 [0.8101744  0.56709461 0.2570201  0.31083467]]


14. Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.96056966 0.76698316 0.05196466 0.89290757 0.87124973 0.24826924
  0.63177262 0.46374921 0.76707225 0.44338203]
 [0.24842129 0.54613029 0.93545891 0.74203045 0.33953046 0.67706178
  0.43993317 0.00850165 0.56840008 0.888496  ]
 [0.66957248 0.58800942 0.30363214 0.54753603 0.31856679 0.42248326
  0.3886181  0.01056804 0.89582183 0.88735061]
 [0.74171713 0.37091243 0.0968546  0.22044527 0.18284768 0.51553744
  0.65907219 0.70306703 0.46138601 0.94755613]
 [0.59397464 0.22474364 0.10718924 0.89757288 0.05766916 0.91735753
  0.94904497 0.6604946  0.15283303 0.05105154]
 [0.93733065 0.40741104 0.39790091 0.43368259 0.90217219 0.95073529
  0.00939634 0.86092763 0.48062146 0.78652141]
 [0.61709028 0.00417909 0.44116302 0.86884205 0.27941244 0.77653963
  0.32472133 0.60810919 0.65208902 0.72908248]
 [0.73620645 0.11075692 0.272515   0.78984961 0.19971725 0.69193465
  0.63619984 0.86796411 0.05274678 0.07753537]
 [0.75106193 0.85114017 0.89597395 0.05065669 0.12387795 0.18622

15. Write a NumPy program to generate 8 random integers between 100 and 300

In [ ]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[291 257 177 242 102 156 230 120]


16. Write a NumPy program to create a random integer nos of size 20 and sort it.

In [ ]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.13379268 0.0112629  0.11136029 0.39246852 0.95033293 0.22196726
 0.07042969 0.4888782  0.8522031  0.0139328  0.01527421 0.22504374
 0.19814965 0.39407236 0.32337489 0.78643552 0.46154745 0.41647646
 0.91981875 0.79736514]
Sorted array:
[0.0112629  0.0139328  0.01527421 0.07042969 0.11136029 0.13379268
 0.19814965 0.22196726 0.22504374 0.32337489 0.39246852 0.39407236
 0.41647646 0.46154745 0.4888782  0.78643552 0.79736514 0.8522031
 0.91981875 0.95033293]
